import fs from 'fs'; 
import https from 'https'; 
import path from 'path'; 
import express from 'express'; 
import cors from 'cors'; 
import helmet from 'helmet'; 
import morgan from 'morgan'; 
import dotenv from 'dotenv'; 
import router from './routes/index.js'; 
dotenv.config();
const app=express(); 
app.use(helmet({crossOriginResourcePolicy:false})); 
app.use(cors({origin:process.env.CLIENT_URL,credentials:true})); 
app.use(express.json()); app.use(morgan('dev')); 
app.use('/uploads', express.static(path.resolve('uploads')));
app.use('/products', express.static(path.resolve('uploads/products'))); 
app.use('/api',router); 
app.get('/api/health',(_,res)=>res.json({status:'ok'}));
const port=process.env.HTTPS_PORT||5000; const opts={key:fs.readFileSync('certs/key.pem'),cert:fs.readFileSync('certs/cert.pem')}; https.createServer(opts,app).listen(port,()=>console.log(`HTTPS API: https://localhost:${port}`));
